stages:
  dev:
    memorySize: 256
    timeout: 30
    reservedConcurrency: 5
    warmup: false
    # Dev-specific environment values
    dbHost: 'devtestecom.c23kqc4606xo.us-east-1.rds.amazonaws.com'
    dbPort: '5432'
    dbName: 'postgres'
    dbUsername: 'postgres'
    dbPassword: 'ehbCXYVfesIcx6Fwdkqz'
    jwtSecret: '3fad63120e09939d9d4f0df62e0349269285d9ddf341b5bfc91d45c29939c8fb52b7b91622e6805f14350eebf8038747f70f2f852795a9f8517e8d5398bd86620734d1e72bc3247bb831807bca5a7aaac0f59a4dcf96b71a4eef51c15ec8324589d4f4d7d4cb26ac813a0ae4816efe03191958d779fcb5366f9ae6bead8df21116706489bf288142037e23dfcf89e0b35f10d08b8edd6359cc2b2e90bf4a554441f40da0f60c3385d824111cc56f6baa675226d06a163d5d2b471d1da8661e83188556d3eab78b3db155e9d1e29b6ade9dcb0dd92b084e00baa0d1ca9475fd7ea1368d3fdd37c1d3693812c8cc45a70394eea6964fbd4802d3a7703a081bb807'
    jwtExpiresIn: '1y'
    redisUrl: 'redis://localhost:6379'
    appVersion: '1.0.0'
    s3BucketName: 'devtestecom'
    securityGroupId: 'sg-027203f6dffc0647e' 
    subnetId1: 'subnet-0e5c34395358ff3e7' 
    subnetId2: 'subnet-0963283b2f46ae343' 
    frontendUrl: 'http://localhost:3000'
 
    # memorySize: 1024
    # timeout: 30
    # reservedConcurrency: 50
    # warmup: true
    # # Production-specific environment values (replace placeholders)
    # dbHost: 'YOUR_PROD_DB_HOST'
    # dbPort: 'YOUR_PROD_DB_PORT'
    # dbName: 'prodtestecom'
    # dbUsername: 'YOUR_PROD_DB_USERNAME'
    # dbPassword: 'YOUR_PROD_DB_PASSWORD'
    # jwtSecret: 'YOUR_PROD_JWT_SECRET'
    # jwtExpiresIn: '24h'
    # redisUrl: 'YOUR_PROD_REDIS_URL' # or empty if not used: ''
    # appVersion: 'YOUR_PROD_APP_VERSION' # e.g., git sha
    # s3BucketName: 'prodtestecom'
    # securityGroupId: 'YOUR_PROD_SECURITY_GROUP_ID'
    # subnetId1: 'YOUR_PROD_SUBNET_ID_1'
    # subnetId2: 'YOUR_PROD_SUBNET_ID_2'
    # frontendUrl: 'YOUR_PROD_FRONTEND_URL' 